.PHONY: all clean

CFLAGS+=-stc=C++11
LDFLAGS+=-lm     # link to math library

TARGET=test train 

all: $(TARGET) 
# type make/make all to compile test_hmm

run: 


clean:
	$(RM) $(TARGET)   # type make clean to remove the compiled file
